# Spring Application Configuration
spring.profiles.active=${APP_PROFILE:local}
spring.application.name=tui_khon_be

# Server Configuration
server.port=${SERVER_PORT:8080}

# Timezone Configuration (Global UTC)
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logging Path Configuration
logging.file.path=${LOG_PATH:./logs}
